// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5LwQLKUkRwM2rsYuQkapZntLBHdDYOw',
    appId: '1:981685586958:web:2818070b8b14ab2fd7805f',
    messagingSenderId: '981685586958',
    projectId: 'manju-cfa8e',
    authDomain: 'manju-cfa8e.firebaseapp.com',
    databaseURL: 'https://manju-cfa8e-default-rtdb.firebaseio.com',
    storageBucket: 'manju-cfa8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqIZ2TYCFDncqu_XT5Csz6SXgkk5JcY_4',
    appId: '1:981685586958:android:d815ac274c4d4b63d7805f',
    messagingSenderId: '981685586958',
    projectId: 'manju-cfa8e',
    databaseURL: 'https://manju-cfa8e-default-rtdb.firebaseio.com',
    storageBucket: 'manju-cfa8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKT9X2JLJzhzGsgly4wmIWd7kMkCtgETg',
    appId: '1:981685586958:ios:d6ee06fecc4bf09cd7805f',
    messagingSenderId: '981685586958',
    projectId: 'manju-cfa8e',
    databaseURL: 'https://manju-cfa8e-default-rtdb.firebaseio.com',
    storageBucket: 'manju-cfa8e.appspot.com',
    iosBundleId: 'edu.cuny.ccny.csc322.spring2024.m.manju.manjuThree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKT9X2JLJzhzGsgly4wmIWd7kMkCtgETg',
    appId: '1:981685586958:ios:d6ee06fecc4bf09cd7805f',
    messagingSenderId: '981685586958',
    projectId: 'manju-cfa8e',
    databaseURL: 'https://manju-cfa8e-default-rtdb.firebaseio.com',
    storageBucket: 'manju-cfa8e.appspot.com',
    iosBundleId: 'edu.cuny.ccny.csc322.spring2024.m.manju.manjuThree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg5LwQLKUkRwM2rsYuQkapZntLBHdDYOw',
    appId: '1:981685586958:web:0c50bbe4c8264ad5d7805f',
    messagingSenderId: '981685586958',
    projectId: 'manju-cfa8e',
    authDomain: 'manju-cfa8e.firebaseapp.com',
    databaseURL: 'https://manju-cfa8e-default-rtdb.firebaseio.com',
    storageBucket: 'manju-cfa8e.appspot.com',
  );
}
